import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ProductShelf } from "@/components/ProductShelf";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex flex-col justify-center items-center w-full">
          <header className="flex justify-center items-center w-full p-6 border-b border-slate-200">
            <h1 className="text-slate-500 font-bold text-xl">Brand</h1>
          </header>
          <div className="xl:container flex flex-col">
            {children}
            <ProductShelf />
          </div>
        </div>
      </body>
    </html>
  );
}
